Order pages now update in realtime
muccc-rs/napoli-rust pull request #2
Opened 2023-05-23 22:17 UTC by git-commit

Look @Rahix!

2023-05-23 23:22 UTC, Rahix requested changes
LGTM :+1: :+1: :+1:

2023-05-23 23:22 UTC, Rahix commented on napoli-pain/src/components/order_details/order_details.rs
> +                        let o: npb::Order = single_order_reply_result.ok().unwrap().order.unwrap();
`.ok().unwrap()` discards the error message and just panics with `None` which is less descriptive.  `.unwrap()` the result directly instead.

2023-05-23 23:22 UTC, Rahix commented on napoli-pain/src/components/order_details/order_details.rs
> +                        Self::Message::GotStreamingOrderUpdate(o)
If you were to bubble up the error:

```rust
match single_order_reply_result {
    Ok(SingleOrderReply { order: Some(o), .. }) => Self::Message::GotStreamingOrderUpdate(o),
    Err(e) => {
        console_log!("Error parsing reply on update stream: {e:?}");
        Self::Message::SetNonLiveUpdated
    }
}
```

2023-05-23 23:22 UTC, Rahix commented on napoli-pain/src/service.rs
> +        let request = GetOrderRequest { order_id };
```suggestion
        let request = npb_grpc::GetOrderRequest { order_id };
```

2023-05-23 23:22 UTC, Rahix commented on napoli-pain/src/service.rs
> +use napoli_lib::napoli::{order_service_client as npb_grpc, GetOrderRequest};
Revert this change, don't import `GetOrderRequest` directly.

2023-05-23 23:22 UTC, Rahix commented on napoli-pain/src/service.rs
>  use napoli_lib::napoli::{self as npb, ObjectId};
Please change to

```rust
use napoli_lib::napoli as npb;
```

2023-05-23 23:22 UTC, Rahix commented on napoli-server/src/server.rs
>  };
Should be

```rust
use napoli_lib::napoli as npb;
```

2023-05-23 23:22 UTC, Rahix commented on napoli-server/src/server.rs
> +    // TODO Clean up TXs that are no longer used
Still relevant?

2023-05-23 23:22 UTC, Rahix commented on napoli-server/src/server.rs
> +            Box::pin(output_stream) as Self::StreamOrderUpdatesStream
Is that `as` really needed here?

2023-05-23 23:22 UTC, Rahix commented on napoli-server/src/server.rs
> +        let (tx, rx) = mpsc::channel(128);
This should really be a <https://docs.rs/tokio/1.28.1/tokio/sync/watch/index.html>

2023-05-23 23:23 UTC, Rahix requested changes
0xBAD

2023-05-24 02:02 UTC, git-commit commented on napoli-server/src/server.rs
> +            Box::pin(output_stream) as Self::StreamOrderUpdatesStream
Seems so

```rust
Ok(Response::new(
    Box::pin(output_stream).into()
))
```

yields
```rust
error[E0277]: the trait bound `Pin<Box<dyn Stream<Item = Result<SingleOrderReply, Status>> + std::marker::Send>>: From<Pin
 <Box<ReceiverStream<Result<SingleOrderReply, Status>>>>>` is not satisfied
   --> napoli-server/src/server.rs:58:37
    |
 58 |             Box::pin(output_stream).into()
    |                                     ^^^^ the trait `From<Pin<Box<ReceiverStream<Result<SingleOrderReply, Status>>>>>` is
  not implemented for `Pin<Box<dyn Stream<Item = Result<SingleOrderReply, Status>> + std::marker::Send>>`
```

2023-05-31 02:22 UTC, Rahix reviewed
:rocket: :rocket: :rocket: :rocket: :rocket: :rocket:

2023-05-31 02:22 UTC, Rahix commented on napoli-server/src/server.rs
> +        let rx = match sender {
Being pedantic: `sender_mutex` is actually the value inside the mutex, i.e. the map of update senders.  So i'd rename this slightly:

```suggestion
        let mut senders = self.active_order_update_senders.lock().await;
        let rx = match senders.entry(order_id) {
```

2023-05-31 02:22 UTC, Rahix commented on napoli-server/src/server.rs
> +        };
The entry API is just so nice, I love this :+1:

2023-05-31 02:22 UTC, Rahix commented on napoli-server/src/main.rs
> +    gc_delay: u64,
We can drop this, right?

2023-05-31 02:22 UTC, Rahix commented on napoli-pain/src/components/order_details/order_details.rs
> +                                println!("Error in stream: {:?}", e);
I don't think this `println!()` is properly sent to the browser console, or is it?

2023-05-31 02:22 UTC, Rahix commented on napoli-pain/src/components/order_details/live_streaming_indicator.rs
> +    )
I think you can make your life a bit easier by just storing an empty string in `hover` instead of the `Option<>`.

2023-05-31 02:24 UTC, Rahix commented on napoli-server/src/server.rs
> +            Box::pin(output_stream) as Self::StreamOrderUpdatesStream
cursed... let's look at this again at the next meetup, i'd be curious to dissect this.

2023-05-31 20:08 UTC, git-commit commented on napoli-server/src/server.rs
> +            Box::pin(output_stream) as Self::StreamOrderUpdatesStream
Yep, let's look at this in the next session

2023-06-01 00:04 UTC, Rahix approved these changes
Send it!

2023-06-01 12:37 UTC, merged